// Code generated by protoc-gen-go. DO NOT EDIT.
// source: candidatura.proto

package descritor

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Candidatura struct {
	Legislatura           int64      `protobuf:"varint,1,opt,name=Legislatura,proto3" json:"leg" csv:"leg"`
	Cargo                 string     `protobuf:"bytes,2,opt,name=Cargo,proto3" json:"cargo" csv:"cargo"`
	UF                    string     `protobuf:"bytes,3,opt,name=UF,proto3" json:"uf" csv:"uf"`
	Municipio             string     `protobuf:"bytes,4,opt,name=Municipio,proto3" json:"municipio" csv:"municipio"`
	NumeroUrna            int64      `protobuf:"varint,5,opt,name=NumeroUrna,proto3" json:"numero_urna" csv:"numero_urna"`
	NomeUrna              string     `protobuf:"bytes,6,opt,name=NomeUrna,proto3" json:"nome_urna" csv:"nome_urna"`
	Aptdao                string     `protobuf:"bytes,7,opt,name=Aptdao,proto3" json:"aptidao" csv:"aptidao"`
	Deferimento           string     `protobuf:"bytes,8,opt,name=Deferimento,proto3" json:"deferimento" csv:"deferimento"`
	TipoAgremiacao        string     `protobuf:"bytes,9,opt,name=TipoAgremiacao,proto3" json:"tipo_agremiacao" csv:"tipo_agremiacao"`
	NumeroPartido         int64      `protobuf:"varint,10,opt,name=NumeroPartido,proto3" json:"numero_partio" csv:"numero_partido"`
	LegendaPartido        string     `protobuf:"bytes,11,opt,name=LegendaPartido,proto3" json:"legenda_partido" csv:"legenda_partido"`
	NomePartido           string     `protobuf:"bytes,12,opt,name=NomePartido,proto3" json:"nome_partido" csv:"nome_partido"`
	NomeColigacao         string     `protobuf:"bytes,13,opt,name=NomeColigacao,proto3" json:"nome_coligacao" csv:"nome_coligacao"`
	PartidosColigacao     string     `protobuf:"bytes,14,opt,name=PartidosColigacao,proto3" json:"partidos_coligacao" csv:"partidos_coligacao"`
	DeclarouBens          bool       `protobuf:"varint,15,opt,name=DeclarouBens,proto3" json:"declarou_bens" csv:"declarou_bens"`
	SituacaoPrimeiroTurno string     `protobuf:"bytes,16,opt,name=SituacaoPrimeiroTurno,proto3" json:"situacao_1turno" csv:"situacao_1turno"`
	SituacaoSegundoTurno  string     `protobuf:"bytes,17,opt,name=SituacaoSegundoTurno,proto3" json:"situacao_2turno" csv:"situacao_2turno"`
	SequencialCandidato   string     `protobuf:"bytes,18,opt,name=SequencialCandidato,proto3" json:"sequencial_candidato" csv:"sequencial_candidato"`
	Descricao             string     `protobuf:"bytes,19,opt,name=Descricao,proto3" json:"descricao" csv:"descricao"`
	Candidato             *Candidato `protobuf:"bytes,20,opt,name=Candidato,proto3" json:"candidato" csv:"-"`
	XXX_NoUnkeyedLiteral  struct{}   `json:"-" csv:"-"`
	XXX_unrecognized      []byte     `json:"-" csv:"-"`
	XXX_sizecache         int32      `json:"-" csv:"-"`
}

func (m *Candidatura) Reset()         { *m = Candidatura{} }
func (m *Candidatura) String() string { return proto.CompactTextString(m) }
func (*Candidatura) ProtoMessage()    {}
func (*Candidatura) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc4fb5b387980952, []int{0}
}

func (m *Candidatura) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Candidatura.Unmarshal(m, b)
}
func (m *Candidatura) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Candidatura.Marshal(b, m, deterministic)
}
func (m *Candidatura) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Candidatura.Merge(m, src)
}
func (m *Candidatura) XXX_Size() int {
	return xxx_messageInfo_Candidatura.Size(m)
}
func (m *Candidatura) XXX_DiscardUnknown() {
	xxx_messageInfo_Candidatura.DiscardUnknown(m)
}

var xxx_messageInfo_Candidatura proto.InternalMessageInfo

func (m *Candidatura) GetLegislatura() int64 {
	if m != nil {
		return m.Legislatura
	}
	return 0
}

func (m *Candidatura) GetCargo() string {
	if m != nil {
		return m.Cargo
	}
	return ""
}

func (m *Candidatura) GetUF() string {
	if m != nil {
		return m.UF
	}
	return ""
}

func (m *Candidatura) GetMunicipio() string {
	if m != nil {
		return m.Municipio
	}
	return ""
}

func (m *Candidatura) GetNumeroUrna() int64 {
	if m != nil {
		return m.NumeroUrna
	}
	return 0
}

func (m *Candidatura) GetNomeUrna() string {
	if m != nil {
		return m.NomeUrna
	}
	return ""
}

func (m *Candidatura) GetAptdao() string {
	if m != nil {
		return m.Aptdao
	}
	return ""
}

func (m *Candidatura) GetDeferimento() string {
	if m != nil {
		return m.Deferimento
	}
	return ""
}

func (m *Candidatura) GetTipoAgremiacao() string {
	if m != nil {
		return m.TipoAgremiacao
	}
	return ""
}

func (m *Candidatura) GetNumeroPartido() int64 {
	if m != nil {
		return m.NumeroPartido
	}
	return 0
}

func (m *Candidatura) GetLegendaPartido() string {
	if m != nil {
		return m.LegendaPartido
	}
	return ""
}

func (m *Candidatura) GetNomePartido() string {
	if m != nil {
		return m.NomePartido
	}
	return ""
}

func (m *Candidatura) GetNomeColigacao() string {
	if m != nil {
		return m.NomeColigacao
	}
	return ""
}

func (m *Candidatura) GetPartidosColigacao() string {
	if m != nil {
		return m.PartidosColigacao
	}
	return ""
}

func (m *Candidatura) GetDeclarouBens() bool {
	if m != nil {
		return m.DeclarouBens
	}
	return false
}

func (m *Candidatura) GetSituacaoPrimeiroTurno() string {
	if m != nil {
		return m.SituacaoPrimeiroTurno
	}
	return ""
}

func (m *Candidatura) GetSituacaoSegundoTurno() string {
	if m != nil {
		return m.SituacaoSegundoTurno
	}
	return ""
}

func (m *Candidatura) GetSequencialCandidato() string {
	if m != nil {
		return m.SequencialCandidato
	}
	return ""
}

func (m *Candidatura) GetDescricao() string {
	if m != nil {
		return m.Descricao
	}
	return ""
}

func (m *Candidatura) GetCandidato() *Candidato {
	if m != nil {
		return m.Candidato
	}
	return nil
}

type Candidato struct {
	UF                   string               `protobuf:"bytes,1,opt,name=UF,proto3" json:"uf_origem" csv:"uf_origem"`
	Municipio            string               `protobuf:"bytes,2,opt,name=Municipio,proto3" json:"municipio_origem" csv:"municipio_origem"`
	Nascimento           *timestamp.Timestamp `protobuf:"bytes,3,opt,name=Nascimento,proto3" json:"nascimento" csv:"nascimento"`
	TituloEleitoral      string               `protobuf:"bytes,4,opt,name=TituloEleitoral,proto3" json:"titulo_eleitoral" csv:"titulo_eleitoral"`
	Genero               string               `protobuf:"bytes,5,opt,name=Genero,proto3" json:"genero" csv:"genero"`
	GrauInstrucao        string               `protobuf:"bytes,6,opt,name=GrauInstrucao,proto3" json:"grau_instrucao" csv:"grau_instrucao"`
	EstadoCivil          string               `protobuf:"bytes,7,opt,name=EstadoCivil,proto3" json:"estado_civil" csv:"estado_civil"`
	Raca                 string               `protobuf:"bytes,8,opt,name=Raca,proto3" json:"raca" csv:"raca"`
	Ocupacao             string               `protobuf:"bytes,9,opt,name=Ocupacao,proto3" json:"ocupacao" csv:"ocupacao"`
	CPF                  string               `protobuf:"bytes,10,opt,name=CPF,proto3" json:"cpf" csv:"cpf"`
	Nome                 string               `protobuf:"bytes,11,opt,name=Nome,proto3" json:"nome" csv:"nome"`
	Email                string               `protobuf:"bytes,12,opt,name=Email,proto3" json:"email" csv:"email"`
	PhotoURL             string               `protobuf:"bytes,13,opt,name=PhotoURL,proto3" json:"photo_url" csv:"photo_url"`
	Site                 string               `protobuf:"bytes,14,opt,name=Site,proto3" json:"site" csv:"site"`
	Instagram            string               `protobuf:"bytes,15,opt,name=Instagram,proto3" json:"instagram" csv:"instagram"`
	Twitter              string               `protobuf:"bytes,16,opt,name=Twitter,proto3" json:"twitter" csv:"twitter"`
	Facebook             string               `protobuf:"bytes,17,opt,name=Facebook,proto3" json:"facebook" csv:"facebook"`
	Biografia            string               `protobuf:"bytes,18,opt,name=Biografia,proto3" json:"biografia" csv:"biografia"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" csv:"-"`
	XXX_unrecognized     []byte               `json:"-" csv:"-"`
	XXX_sizecache        int32                `json:"-" csv:"-"`
}

func (m *Candidato) Reset()         { *m = Candidato{} }
func (m *Candidato) String() string { return proto.CompactTextString(m) }
func (*Candidato) ProtoMessage()    {}
func (*Candidato) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc4fb5b387980952, []int{1}
}

func (m *Candidato) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Candidato.Unmarshal(m, b)
}
func (m *Candidato) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Candidato.Marshal(b, m, deterministic)
}
func (m *Candidato) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Candidato.Merge(m, src)
}
func (m *Candidato) XXX_Size() int {
	return xxx_messageInfo_Candidato.Size(m)
}
func (m *Candidato) XXX_DiscardUnknown() {
	xxx_messageInfo_Candidato.DiscardUnknown(m)
}

var xxx_messageInfo_Candidato proto.InternalMessageInfo

func (m *Candidato) GetUF() string {
	if m != nil {
		return m.UF
	}
	return ""
}

func (m *Candidato) GetMunicipio() string {
	if m != nil {
		return m.Municipio
	}
	return ""
}

func (m *Candidato) GetNascimento() *timestamp.Timestamp {
	if m != nil {
		return m.Nascimento
	}
	return nil
}

func (m *Candidato) GetTituloEleitoral() string {
	if m != nil {
		return m.TituloEleitoral
	}
	return ""
}

func (m *Candidato) GetGenero() string {
	if m != nil {
		return m.Genero
	}
	return ""
}

func (m *Candidato) GetGrauInstrucao() string {
	if m != nil {
		return m.GrauInstrucao
	}
	return ""
}

func (m *Candidato) GetEstadoCivil() string {
	if m != nil {
		return m.EstadoCivil
	}
	return ""
}

func (m *Candidato) GetRaca() string {
	if m != nil {
		return m.Raca
	}
	return ""
}

func (m *Candidato) GetOcupacao() string {
	if m != nil {
		return m.Ocupacao
	}
	return ""
}

func (m *Candidato) GetCPF() string {
	if m != nil {
		return m.CPF
	}
	return ""
}

func (m *Candidato) GetNome() string {
	if m != nil {
		return m.Nome
	}
	return ""
}

func (m *Candidato) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Candidato) GetPhotoURL() string {
	if m != nil {
		return m.PhotoURL
	}
	return ""
}

func (m *Candidato) GetSite() string {
	if m != nil {
		return m.Site
	}
	return ""
}

func (m *Candidato) GetInstagram() string {
	if m != nil {
		return m.Instagram
	}
	return ""
}

func (m *Candidato) GetTwitter() string {
	if m != nil {
		return m.Twitter
	}
	return ""
}

func (m *Candidato) GetFacebook() string {
	if m != nil {
		return m.Facebook
	}
	return ""
}

func (m *Candidato) GetBiografia() string {
	if m != nil {
		return m.Biografia
	}
	return ""
}

func init() {
	proto.RegisterType((*Candidatura)(nil), "descritor.Candidatura")
	proto.RegisterType((*Candidato)(nil), "descritor.Candidato")
}

func init() { proto.RegisterFile("candidatura.proto", fileDescriptor_bc4fb5b387980952) }

var fileDescriptor_bc4fb5b387980952 = []byte{
	// 634 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x94, 0xdb, 0x6e, 0x13, 0x31,
	0x10, 0x86, 0x95, 0xa4, 0xa7, 0x75, 0x7a, 0x74, 0x03, 0xb2, 0x2a, 0x04, 0x51, 0x85, 0x50, 0x2e,
	0x50, 0x8a, 0x0a, 0x57, 0xdc, 0xb5, 0x69, 0x53, 0x21, 0x95, 0x12, 0x6d, 0x92, 0x07, 0x98, 0xee,
	0xba, 0x8b, 0xc5, 0xee, 0x4e, 0xf0, 0xda, 0xf0, 0x14, 0x3c, 0x27, 0xaf, 0x81, 0x3c, 0xeb, 0x3d,
	0xa4, 0xe4, 0xce, 0xf3, 0xcf, 0xc1, 0xb3, 0xce, 0xf7, 0x87, 0x9d, 0x44, 0x90, 0xc7, 0x2a, 0x06,
	0x63, 0x35, 0x8c, 0x57, 0x1a, 0x0d, 0xf2, 0x20, 0x96, 0x45, 0xa4, 0x95, 0x41, 0x7d, 0xf6, 0x26,
	0x41, 0x4c, 0x52, 0x79, 0x41, 0x89, 0x47, 0xfb, 0x74, 0x61, 0x54, 0x26, 0x0b, 0x03, 0xd9, 0xaa,
	0xac, 0x3d, 0xff, 0xbb, 0xcd, 0xfa, 0x93, 0x66, 0x02, 0x1f, 0xb2, 0xfe, 0xbd, 0x4c, 0x54, 0x91,
	0x52, 0x28, 0x3a, 0xc3, 0xce, 0xa8, 0x17, 0xb6, 0x25, 0x3e, 0x60, 0xdb, 0x13, 0xd0, 0x09, 0x8a,
	0xee, 0xb0, 0x33, 0x0a, 0xc2, 0x32, 0xe0, 0x87, 0xac, 0xbb, 0x9c, 0x8a, 0x1e, 0x49, 0xdd, 0xe5,
	0x94, 0xbf, 0x62, 0xc1, 0x57, 0x9b, 0xab, 0x48, 0xad, 0x14, 0x8a, 0x2d, 0x92, 0x1b, 0x81, 0xbf,
	0x66, 0xec, 0xc1, 0x66, 0x52, 0xe3, 0x52, 0xe7, 0x20, 0xb6, 0xe9, 0x92, 0x96, 0xc2, 0xcf, 0xd8,
	0xde, 0x03, 0x66, 0x92, 0xb2, 0x3b, 0xd4, 0x5c, 0xc7, 0xfc, 0x25, 0xdb, 0xb9, 0x5a, 0x99, 0x18,
	0x50, 0xec, 0x52, 0xc6, 0x47, 0x6e, 0xf3, 0x1b, 0xf9, 0x24, 0xb5, 0xca, 0x64, 0x6e, 0x50, 0xec,
	0x51, 0xb2, 0x2d, 0xf1, 0x77, 0xec, 0x70, 0xa1, 0x56, 0x78, 0x95, 0x68, 0x99, 0x29, 0x88, 0x00,
	0x45, 0x40, 0x45, 0xcf, 0x54, 0xfe, 0x96, 0x1d, 0x94, 0xbb, 0xcc, 0x40, 0x1b, 0x15, 0xa3, 0x60,
	0xb4, 0xe0, 0xba, 0xe8, 0xa6, 0xdd, 0xcb, 0x44, 0xe6, 0x31, 0x54, 0x65, 0xfd, 0x72, 0xda, 0xba,
	0xea, 0xf6, 0x72, 0xbb, 0x57, 0x45, 0xfb, 0xe5, 0x5e, 0x2d, 0x89, 0xee, 0xc3, 0x4c, 0x4e, 0x30,
	0x55, 0x09, 0xad, 0x75, 0x40, 0x35, 0xeb, 0x22, 0x7f, 0xcf, 0x4e, 0x7c, 0x43, 0xd1, 0x54, 0x1e,
	0x52, 0xe5, 0xff, 0x09, 0x7e, 0xce, 0xf6, 0x6f, 0x64, 0x94, 0x82, 0x46, 0x7b, 0x2d, 0xf3, 0x42,
	0x1c, 0x0d, 0x3b, 0xa3, 0xbd, 0x70, 0x4d, 0xe3, 0x9f, 0xd8, 0x8b, 0xb9, 0x32, 0xd6, 0xd5, 0xcf,
	0xdc, 0x1b, 0x29, 0x8d, 0x0b, 0xab, 0x73, 0x14, 0xc7, 0x34, 0x75, 0x73, 0x92, 0x5f, 0xb2, 0x41,
	0x95, 0x98, 0xcb, 0xc4, 0xe6, 0xb1, 0x6f, 0x3a, 0xa1, 0xa6, 0x8d, 0x39, 0xfe, 0x81, 0x9d, 0xce,
	0xe5, 0x4f, 0x2b, 0xf3, 0x48, 0x41, 0x5a, 0xe1, 0x86, 0x82, 0x53, 0xcb, 0xa6, 0x94, 0xe3, 0xe7,
	0x86, 0x28, 0x76, 0x5f, 0x79, 0x5a, 0xf2, 0x53, 0x0b, 0xfc, 0x92, 0x05, 0xcd, 0x94, 0xc1, 0xb0,
	0x33, 0xea, 0x5f, 0x0e, 0xc6, 0x35, 0xf5, 0xe3, 0x3a, 0x17, 0x36, 0x65, 0xe7, 0x7f, 0xb6, 0x5a,
	0x4d, 0x9e, 0xd7, 0xce, 0x66, 0x5e, 0xbb, 0xcf, 0x79, 0xfd, 0xcc, 0xd8, 0x03, 0x14, 0x91, 0x47,
	0xab, 0x47, 0x17, 0x9e, 0x8d, 0x4b, 0x6f, 0x8d, 0x2b, 0x6f, 0x8d, 0x17, 0x95, 0xb7, 0xc2, 0x56,
	0x35, 0x1f, 0xb1, 0xa3, 0x85, 0x32, 0x36, 0xc5, 0xdb, 0x54, 0xba, 0xed, 0x20, 0xf5, 0x7e, 0x78,
	0x2e, 0x3b, 0xb2, 0xef, 0x64, 0x2e, 0x35, 0x92, 0x23, 0x82, 0xd0, 0x47, 0x8e, 0x8f, 0x3b, 0x0d,
	0xf6, 0x4b, 0x5e, 0x18, 0x6d, 0xdd, 0x7b, 0x94, 0x96, 0x58, 0x17, 0x1d, 0x67, 0xb7, 0x85, 0x81,
	0x18, 0x27, 0xea, 0x97, 0x4a, 0xbd, 0x39, 0xda, 0x12, 0xe7, 0x6c, 0x2b, 0x84, 0x08, 0xbc, 0x35,
	0xe8, 0xec, 0x9c, 0xf6, 0x2d, 0xb2, 0xab, 0x96, 0x1b, 0xea, 0x98, 0x1f, 0xb3, 0xde, 0x64, 0x36,
	0x25, 0xfa, 0x83, 0xd0, 0x1d, 0xdd, 0x04, 0x07, 0xa5, 0x27, 0x9d, 0xce, 0xee, 0xff, 0xe0, 0x36,
	0x03, 0x95, 0x7a, 0xb2, 0xcb, 0xc0, 0xcd, 0x9d, 0x7d, 0x47, 0x83, 0xcb, 0xf0, 0xde, 0xe3, 0x5c,
	0xc7, 0x6e, 0xca, 0x5c, 0x19, 0xe9, 0xe1, 0xa5, 0xb3, 0x7b, 0x7f, 0xf7, 0x29, 0x90, 0x68, 0xc8,
	0x08, 0xd6, 0x20, 0x6c, 0x04, 0x2e, 0xd8, 0xee, 0xe2, 0xb7, 0x32, 0x46, 0x6a, 0xcf, 0x66, 0x15,
	0xba, 0x7b, 0xa6, 0x10, 0xc9, 0x47, 0xc4, 0x1f, 0x9e, 0xc0, 0x3a, 0x76, 0x33, 0xaf, 0x15, 0x26,
	0x1a, 0x9e, 0x14, 0x78, 0xd6, 0x1a, 0xe1, 0x71, 0x87, 0x7e, 0xb7, 0x8f, 0xff, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x5e, 0xaa, 0xa4, 0x56, 0x41, 0x05, 0x00, 0x00,
}
